defmodule Dota.Hero do
  @heroes %{
      1 => %{"id" =>   1, "localized_name" => "Anti-Mage",           "name" => "antimage"},
      2 => %{"id" =>   2, "localized_name" => "Axe",                 "name" => "axe"},
      3 => %{"id" =>   3, "localized_name" => "Bane",                "name" => "bane"},
      4 => %{"id" =>   4, "localized_name" => "Bloodseeker",         "name" => "bloodseeker"},
      5 => %{"id" =>   5, "localized_name" => "Crystal Maiden",      "name" => "crystal_maiden"},
      6 => %{"id" =>   6, "localized_name" => "Drow Ranger",         "name" => "drow_ranger"},
      7 => %{"id" =>   7, "localized_name" => "Earthshaker",         "name" => "earthshaker"},
      8 => %{"id" =>   8, "localized_name" => "Juggernaut",          "name" => "juggernaut"},
      9 => %{"id" =>   9, "localized_name" => "Mirana",              "name" => "mirana"},
     11 => %{"id" =>  11, "localized_name" => "Shadow Fiend",        "name" => "nevermore"},
     10 => %{"id" =>  10, "localized_name" => "Morphling",           "name" => "morphling"},
     12 => %{"id" =>  12, "localized_name" => "Phantom Lancer",      "name" => "phantom_lancer"},
     13 => %{"id" =>  13, "localized_name" => "Puck",                "name" => "puck"},
     14 => %{"id" =>  14, "localized_name" => "Pudge",               "name" => "pudge"},
     15 => %{"id" =>  15, "localized_name" => "Razor",               "name" => "razor"},
     16 => %{"id" =>  16, "localized_name" => "Sand King",           "name" => "sand_king"},
     17 => %{"id" =>  17, "localized_name" => "Storm Spirit",        "name" => "storm_spirit"},
     18 => %{"id" =>  18, "localized_name" => "Sven",                "name" => "sven"},
     19 => %{"id" =>  19, "localized_name" => "Tiny",                "name" => "tiny"},
     20 => %{"id" =>  20, "localized_name" => "Vengeful Spirit",     "name" => "vengefulspirit"},
     21 => %{"id" =>  21, "localized_name" => "Windranger",          "name" => "windrunner"},
     22 => %{"id" =>  22, "localized_name" => "Zeus",                "name" => "zuus"},
     23 => %{"id" =>  23, "localized_name" => "Kunkka",              "name" => "kunkka"},
     25 => %{"id" =>  25, "localized_name" => "Lina",                "name" => "lina"},
     31 => %{"id" =>  31, "localized_name" => "Lich",                "name" => "lich"},
     26 => %{"id" =>  26, "localized_name" => "Lion",                "name" => "lion"},
     27 => %{"id" =>  27, "localized_name" => "Shadow Shaman",       "name" => "shadow_shaman"},
     28 => %{"id" =>  28, "localized_name" => "Slardar",             "name" => "slardar"},
     29 => %{"id" =>  29, "localized_name" => "Tidehunter",          "name" => "tidehunter"},
     30 => %{"id" =>  30, "localized_name" => "Witch Doctor",        "name" => "witch_doctor"},
     32 => %{"id" =>  32, "localized_name" => "Riki",                "name" => "riki"},
     33 => %{"id" =>  33, "localized_name" => "Enigma",              "name" => "enigma"},
     34 => %{"id" =>  34, "localized_name" => "Tinker",              "name" => "tinker"},
     35 => %{"id" =>  35, "localized_name" => "Sniper",              "name" => "sniper"},
     36 => %{"id" =>  36, "localized_name" => "Necrophos",           "name" => "necrolyte"},
     37 => %{"id" =>  37, "localized_name" => "Warlock",             "name" => "warlock"},
     38 => %{"id" =>  38, "localized_name" => "Beastmaster",         "name" => "beastmaster"},
     39 => %{"id" =>  39, "localized_name" => "Queen of Pain",       "name" => "queenofpain"},
     40 => %{"id" =>  40, "localized_name" => "Venomancer",          "name" => "venomancer"},
     41 => %{"id" =>  41, "localized_name" => "Faceless Void",       "name" => "faceless_void"},
     42 => %{"id" =>  42, "localized_name" => "Wraith King",         "name" => "skeleton_king"},
     43 => %{"id" =>  43, "localized_name" => "Death Prophet",       "name" => "death_prophet"},
     44 => %{"id" =>  44, "localized_name" => "Phantom Assassin",    "name" => "phantom_assassin"},
     45 => %{"id" =>  45, "localized_name" => "Pugna",               "name" => "pugna"},
     46 => %{"id" =>  46, "localized_name" => "Templar Assassin",    "name" => "templar_assassin"},
     47 => %{"id" =>  47, "localized_name" => "Viper",               "name" => "viper"},
     48 => %{"id" =>  48, "localized_name" => "Luna",                "name" => "luna"},
     49 => %{"id" =>  49, "localized_name" => "Dragon Knight",       "name" => "dragon_knight"},
     50 => %{"id" =>  50, "localized_name" => "Dazzle",              "name" => "dazzle"},
     51 => %{"id" =>  51, "localized_name" => "Clockwerk",           "name" => "rattletrap"},
     52 => %{"id" =>  52, "localized_name" => "Leshrac",             "name" => "leshrac"},
     53 => %{"id" =>  53, "localized_name" => "Nature's Prophet",    "name" => "furion"},
     54 => %{"id" =>  54, "localized_name" => "Lifestealer",         "name" => "life_stealer"},
     55 => %{"id" =>  55, "localized_name" => "Dark Seer",           "name" => "dark_seer"},
     56 => %{"id" =>  56, "localized_name" => "Clinkz",              "name" => "clinkz"},
     57 => %{"id" =>  57, "localized_name" => "Omniknight",          "name" => "omniknight"},
     58 => %{"id" =>  58, "localized_name" => "Enchantress",         "name" => "enchantress"},
     59 => %{"id" =>  59, "localized_name" => "Huskar",              "name" => "huskar"},
     60 => %{"id" =>  60, "localized_name" => "Night Stalker",       "name" => "night_stalker"},
     61 => %{"id" =>  61, "localized_name" => "Broodmother",         "name" => "broodmother"},
     62 => %{"id" =>  62, "localized_name" => "Bounty Hunter",       "name" => "bounty_hunter"},
     63 => %{"id" =>  63, "localized_name" => "Weaver",              "name" => "weaver"},
     64 => %{"id" =>  64, "localized_name" => "Jakiro",              "name" => "jakiro"},
     65 => %{"id" =>  65, "localized_name" => "Batrider",            "name" => "batrider"},
     66 => %{"id" =>  66, "localized_name" => "Chen",                "name" => "chen"},
     67 => %{"id" =>  67, "localized_name" => "Spectre",             "name" => "spectre"},
     69 => %{"id" =>  69, "localized_name" => "Doom",                "name" => "doom_bringer"},
     68 => %{"id" =>  68, "localized_name" => "Ancient Apparition",  "name" => "ancient_apparition"},
     70 => %{"id" =>  70, "localized_name" => "Ursa",                "name" => "ursa"},
     71 => %{"id" =>  71, "localized_name" => "Spirit Breaker",      "name" => "spirit_breaker"},
     72 => %{"id" =>  72, "localized_name" => "Gyrocopter",          "name" => "gyrocopter"},
     73 => %{"id" =>  73, "localized_name" => "Alchemist",           "name" => "alchemist"},
     74 => %{"id" =>  74, "localized_name" => "Invoker",             "name" => "invoker"},
     75 => %{"id" =>  75, "localized_name" => "Silencer",            "name" => "silencer"},
     76 => %{"id" =>  76, "localized_name" => "Outworld Devourer",   "name" => "obsidian_destroyer"},
     77 => %{"id" =>  77, "localized_name" => "Lycan",               "name" => "lycan"},
     78 => %{"id" =>  78, "localized_name" => "Brewmaster",          "name" => "brewmaster"},
     79 => %{"id" =>  79, "localized_name" => "Shadow Demon",        "name" => "shadow_demon"},
     80 => %{"id" =>  80, "localized_name" => "Lone Druid",          "name" => "lone_druid"},
     81 => %{"id" =>  81, "localized_name" => "Chaos Knight",        "name" => "chaos_knight"},
     82 => %{"id" =>  82, "localized_name" => "Meepo",               "name" => "meepo"},
     83 => %{"id" =>  83, "localized_name" => "Treant Protector",    "name" => "treant"},
     84 => %{"id" =>  84, "localized_name" => "Ogre Magi",           "name" => "ogre_magi"},
     85 => %{"id" =>  85, "localized_name" => "Undying",             "name" => "undying"},
     86 => %{"id" =>  86, "localized_name" => "Rubick",              "name" => "rubick"},
     87 => %{"id" =>  87, "localized_name" => "Disruptor",           "name" => "disruptor"},
     88 => %{"id" =>  88, "localized_name" => "Nyx Assassin",        "name" => "nyx_assassin"},
     89 => %{"id" =>  89, "localized_name" => "Naga Siren",          "name" => "naga_siren"},
     90 => %{"id" =>  90, "localized_name" => "Keeper of the Light", "name" => "keeper_of_the_light"},
     91 => %{"id" =>  91, "localized_name" => "Io",                  "name" => "wisp"},
     92 => %{"id" =>  92, "localized_name" => "Visage",              "name" => "visage"},
     93 => %{"id" =>  93, "localized_name" => "Slark",               "name" => "slark"},
     94 => %{"id" =>  94, "localized_name" => "Medusa",              "name" => "medusa"},
     95 => %{"id" =>  95, "localized_name" => "Troll Warlord",       "name" => "troll_warlord"},
     96 => %{"id" =>  96, "localized_name" => "Centaur Warrunner",   "name" => "centaur"},
     97 => %{"id" =>  97, "localized_name" => "Magnus",              "name" => "magnataur"},
     98 => %{"id" =>  98, "localized_name" => "Timbersaw",           "name" => "shredder"},
     99 => %{"id" =>  99, "localized_name" => "Bristleback",         "name" => "bristleback"},
    100 => %{"id" => 100, "localized_name" => "Tusk",                "name" => "tusk"},
    101 => %{"id" => 101, "localized_name" => "Skywrath Mage",       "name" => "skywrath_mage"},
    102 => %{"id" => 102, "localized_name" => "Abaddon",             "name" => "abaddon"},
    103 => %{"id" => 103, "localized_name" => "Elder Titan",         "name" => "elder_titan"},
    104 => %{"id" => 104, "localized_name" => "Legion Commander",    "name" => "legion_commander"},
    106 => %{"id" => 106, "localized_name" => "Ember Spirit",        "name" => "ember_spirit"},
    107 => %{"id" => 107, "localized_name" => "Earth Spirit",        "name" => "earth_spirit"},
    109 => %{"id" => 109, "localized_name" => "Terrorblade",         "name" => "terrorblade"},
    110 => %{"id" => 110, "localized_name" => "Phoenix",             "name" => "phoenix"},
    111 => %{"id" => 111, "localized_name" => "Oracle",              "name" => "oracle"},
    105 => %{"id" => 105, "localized_name" => "Techies",             "name" => "techies"},
    112 => %{"id" => 112, "localized_name" => "Winter Wyvern",       "name" => "winter_wyvern"}
  }

  def get(id), do: @heroes[id]

  def localized_name(id), do: @heroes[id]["localized_name"]

  def name(id), do: @heroes[id]["name"]

end