defmodule Dota.Item do
  # TODO: define this attribute with meta programming? Maybe just load it in memory?
  @items %{
    263 => %{"id" => 263, "localized_name" => "Hurricane Pike", "name" => "item_hurricane_pike", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1013 => %{"id" => 1013, "localized_name" => "Wizard Cookie", "name" => "item_winter_cookie", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    105 => %{"id" => 105, "localized_name" => "Recipe: Necronomicon", "name" => "item_recipe_necronomicon", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    48 => %{"id" => 48, "localized_name" => "Boots of Travel", "name" => "item_travel_boots", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    230 => %{"id" => 230, "localized_name" => "Recipe: Guardian Greaves", "name" => "item_recipe_guardian_greaves", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    1018 => %{"id" => 1018, "localized_name" => "Greevil Treat", "name" => "item_winter_greevil_treat", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    62 => %{"id" => 62, "localized_name" => "Recipe: Power Treads", "name" => "item_recipe_power_treads", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    205 => %{"id" => 205, "localized_name" => "Recipe: Rod of Atos", "name" => "item_recipe_rod_of_atos", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    11 => %{"id" => 11, "localized_name" => "Quelling Blade", "name" => "item_quelling_blade", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    232 => %{"id" => 232, "localized_name" => "Aether Lens", "name" => "item_aether_lens", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    39 => %{"id" => 39, "localized_name" => "Healing Salve", "name" => "item_flask", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    164 => %{"id" => 164, "localized_name" => "Helm of the Dominator", "name" => "item_helm_of_the_dominator", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    236 => %{"id" => 236, "localized_name" => "Dragon Lance", "name" => "item_dragon_lance", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    217 => %{"id" => 217, "localized_name" => "Recipe: Observer and Sentry Wards", "name" => "item_recipe_ward_dispenser", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    265 => %{"id" => 265, "localized_name" => "Infused Raindrop", "name" => "item_infused_raindrop", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    63 => %{"id" => 63, "localized_name" => "Power Treads", "name" => "item_power_treads", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    34 => %{"id" => 34, "localized_name" => "Magic Stick", "name" => "item_magic_stick", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    248 => %{"id" => 248, "localized_name" => "Recipe: Silver Edge", "name" => "item_recipe_silver_edge", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    130 => %{"id" => 130, "localized_name" => "Recipe: Hood of Defiance", "name" => "item_recipe_hood_of_defiance", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    1011 => %{"id" => 1011, "localized_name" => "Speed Skates", "name" => "item_winter_skates", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    178 => %{"id" => 178, "localized_name" => "Soul Ring", "name" => "item_soul_ring", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    181 => %{"id" => 181, "localized_name" => "Orb of Venom", "name" => "item_orb_of_venom", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    195 => %{"id" => 195, "localized_name" => "Recipe: Diffusal Blade", "name" => "item_recipe_diffusal_blade_2", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    254 => %{"id" => 254, "localized_name" => "Glimmer Cape", "name" => "item_glimmer_cape", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    193 => %{"id" => 193, "localized_name" => "Necronomicon", "name" => "item_necronomicon_2", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    68 => %{"id" => 68, "localized_name" => "Recipe: Perseverance", "name" => "item_recipe_pers", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    154 => %{"id" => 154, "localized_name" => "Sange and Yasha", "name" => "item_sange_and_yasha", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    139 => %{"id" => 139, "localized_name" => "Butterfly", "name" => "item_butterfly", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    176 => %{"id" => 176, "localized_name" => "Ethereal Blade", "name" => "item_ethereal_blade", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1001 => %{"id" => 1001, "localized_name" => "DOTA_Tooltip_Ability_item_mystery_hook", "name" => "item_mystery_hook", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    26 => %{"id" => 26, "localized_name" => "Morbid Mask", "name" => "item_lifesteal", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    78 => %{"id" => 78, "localized_name" => "Recipe: Mekansm", "name" => "item_recipe_mekansm", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    199 => %{"id" => 199, "localized_name" => "Recipe: Dagon", "name" => "item_recipe_dagon_4", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    141 => %{"id" => 141, "localized_name" => "Daedalus", "name" => "item_greater_crit", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    137 => %{"id" => 137, "localized_name" => "Radiance", "name" => "item_radiance", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    138 => %{"id" => 138, "localized_name" => "Recipe: Butterfly", "name" => "item_recipe_butterfly", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    52 => %{"id" => 52, "localized_name" => "Eaglesong", "name" => "item_eagle", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    212 => %{"id" => 212, "localized_name" => "Ring of Aquila", "name" => "item_ring_of_aquila", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    15 => %{"id" => 15, "localized_name" => "Mantle of Intelligence", "name" => "item_mantle", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    136 => %{"id" => 136, "localized_name" => "Recipe: Radiance", "name" => "item_recipe_radiance", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    64 => %{"id" => 64, "localized_name" => "Recipe: Hand of Midas", "name" => "item_recipe_hand_of_midas", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    145 => %{"id" => 145, "localized_name" => "Battle Fury", "name" => "item_bfury", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    75 => %{"id" => 75, "localized_name" => "Wraith Band", "name" => "item_wraith_band", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    81 => %{"id" => 81, "localized_name" => "Vladmir's Offering", "name" => "item_vladmir", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    161 => %{"id" => 161, "localized_name" => "Recipe: Sange", "name" => "item_recipe_sange", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    242 => %{"id" => 242, "localized_name" => "Crimson Guard", "name" => "item_crimson_guard", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1017 => %{"id" => 1017, "localized_name" => "Snow Mushroom", "name" => "item_winter_mushroom", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    214 => %{"id" => 214, "localized_name" => "Tranquil Boots", "name" => "item_tranquil_boots", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    238 => %{"id" => 238, "localized_name" => "Recipe: Iron Talon", "name" => "item_recipe_iron_talon", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    71 => %{"id" => 71, "localized_name" => "Poor Man's Shield", "name" => "item_poor_mans_shield", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    129 => %{"id" => 129, "localized_name" => "Soul Booster", "name" => "item_soul_booster", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    20 => %{"id" => 20, "localized_name" => "Circlet", "name" => "item_circlet", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1007 => %{"id" => 1007, "localized_name" => "Greevil Whistle", "name" => "item_greevil_whistle", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    109 => %{"id" => 109, "localized_name" => "Recipe: Refresher Orb", "name" => "item_recipe_refresher", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    50 => %{"id" => 50, "localized_name" => "Phase Boots", "name" => "item_phase_boots", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    17 => %{"id" => 17, "localized_name" => "Belt of Strength", "name" => "item_belt_of_strength", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    165 => %{"id" => 165, "localized_name" => "Recipe: Maelstrom", "name" => "item_recipe_maelstrom", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    111 => %{"id" => 111, "localized_name" => "Recipe: Assault Cuirass", "name" => "item_recipe_assault", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    190 => %{"id" => 190, "localized_name" => "Veil of Discord", "name" => "item_veil_of_discord", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1019 => %{"id" => 1019, "localized_name" => "Greevil Chow", "name" => "item_winter_greevil_garbage", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    25 => %{"id" => 25, "localized_name" => "Gloves of Haste", "name" => "item_gloves", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    122 => %{"id" => 122, "localized_name" => "Recipe: Linken's Sphere", "name" => "item_recipe_sphere", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    202 => %{"id" => 202, "localized_name" => "Dagon", "name" => "item_dagon_3", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    65 => %{"id" => 65, "localized_name" => "Hand of Midas", "name" => "item_hand_of_midas", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    125 => %{"id" => 125, "localized_name" => "Vanguard", "name" => "item_vanguard", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    98 => %{"id" => 98, "localized_name" => "Orchid Malevolence", "name" => "item_orchid", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    79 => %{"id" => 79, "localized_name" => "Mekansm", "name" => "item_mekansm", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    13 => %{"id" => 13, "localized_name" => "Gauntlets of Strength", "name" => "item_gauntlets", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    191 => %{"id" => 191, "localized_name" => "Recipe: Necronomicon", "name" => "item_recipe_necronomicon_2", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    143 => %{"id" => 143, "localized_name" => "Skull Basher", "name" => "item_basher", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    44 => %{"id" => 44, "localized_name" => "Tango", "name" => "item_tango", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1008 => %{"id" => 1008, "localized_name" => "Greevil Whistle", "name" => "item_greevil_whistle_toggle", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    235 => %{"id" => 235, "localized_name" => "Octarine Core", "name" => "item_octarine_core", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    196 => %{"id" => 196, "localized_name" => "Diffusal Blade", "name" => "item_diffusal_blade_2", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    8 => %{"id" => 8, "localized_name" => "Mithril Hammer", "name" => "item_mithril_hammer", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    162 => %{"id" => 162, "localized_name" => "Sange", "name" => "item_sange", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    207 => %{"id" => 207, "localized_name" => "Recipe: Abyssal Blade", "name" => "item_recipe_abyssal_blade", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    192 => %{"id" => 192, "localized_name" => "Recipe: Necronomicon", "name" => "item_recipe_necronomicon_3", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    1012 => %{"id" => 1012, "localized_name" => "Fruit-bit Cake", "name" => "item_winter_cake", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    99 => %{"id" => 99, "localized_name" => "Recipe: Eul's Scepter of Divinity", "name" => "item_recipe_cyclone", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    36 => %{"id" => 36, "localized_name" => "Magic Wand", "name" => "item_magic_wand", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    67 => %{"id" => 67, "localized_name" => "Oblivion Staff", "name" => "item_oblivion_staff", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    7 => %{"id" => 7, "localized_name" => "Javelin", "name" => "item_javelin", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    244 => %{"id" => 244, "localized_name" => "Wind Lace", "name" => "item_wind_lace", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    66 => %{"id" => 66, "localized_name" => "Recipe: Oblivion Staff", "name" => "item_recipe_oblivion_staff", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    231 => %{"id" => 231, "localized_name" => "Guardian Greaves", "name" => "item_guardian_greaves", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    85 => %{"id" => 85, "localized_name" => "Recipe: Buckler", "name" => "item_recipe_buckler", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    221 => %{"id" => 221, "localized_name" => "Recipe: Lotus Orb", "name" => "item_recipe_lotus_orb", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    150 => %{"id" => 150, "localized_name" => "Recipe: Armlet of Mordiggian", "name" => "item_recipe_armlet", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    76 => %{"id" => 76, "localized_name" => "Recipe: Null Talisman", "name" => "item_recipe_null_talisman", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    1 => %{"id" => 1, "localized_name" => "Blink Dagger", "name" => "item_blink", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    32 => %{"id" => 32, "localized_name" => "Talisman of Evasion", "name" => "item_talisman_of_evasion", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    69 => %{"id" => 69, "localized_name" => "Perseverance", "name" => "item_pers", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    37 => %{"id" => 37, "localized_name" => "Ghost Scepter", "name" => "item_ghost", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    253 => %{"id" => 253, "localized_name" => "Recipe: Glimmer Cape", "name" => "item_recipe_glimmer_cape", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    126 => %{"id" => 126, "localized_name" => "Recipe: Blade Mail", "name" => "item_recipe_blade_mail", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    175 => %{"id" => 175, "localized_name" => "Recipe: Ethereal Blade", "name" => "item_recipe_ethereal_blade", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    35 => %{"id" => 35, "localized_name" => "Recipe: Magic Wand", "name" => "item_recipe_magic_wand", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    84 => %{"id" => 84, "localized_name" => "Flying Courier", "name" => "item_flying_courier", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    186 => %{"id" => 186, "localized_name" => "Recipe: Medallion of Courage", "name" => "item_recipe_medallion_of_courage", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    239 => %{"id" => 239, "localized_name" => "Iron Talon", "name" => "item_iron_talon", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    104 => %{"id" => 104, "localized_name" => "Dagon", "name" => "item_dagon", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    156 => %{"id" => 156, "localized_name" => "Satanic", "name" => "item_satanic", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    3 => %{"id" => 3, "localized_name" => "Broadsword", "name" => "item_broadsword", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    119 => %{"id" => 119, "localized_name" => "Shiva's Guard", "name" => "item_shivas_guard", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    194 => %{"id" => 194, "localized_name" => "Necronomicon", "name" => "item_necronomicon_3", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    45 => %{"id" => 45, "localized_name" => "Animal Courier", "name" => "item_courier", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    163 => %{"id" => 163, "localized_name" => "Recipe: Helm of the Dominator", "name" => "item_recipe_helm_of_the_dominator", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    172 => %{"id" => 172, "localized_name" => "Mask of Madness", "name" => "item_mask_of_madness", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    55 => %{"id" => 55, "localized_name" => "Hyperstone", "name" => "item_hyperstone", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    158 => %{"id" => 158, "localized_name" => "Mjollnir", "name" => "item_mjollnir", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    6 => %{"id" => 6, "localized_name" => "Helm of Iron Will", "name" => "item_helm_of_iron_will", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    2 => %{"id" => 2, "localized_name" => "Blades of Attack", "name" => "item_blades_of_attack", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    245 => %{"id" => 245, "localized_name" => "Recipe: Bloodthorn", "name" => "item_recipe_bloodthorn", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    94 => %{"id" => 94, "localized_name" => "Headdress", "name" => "item_headdress", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    49 => %{"id" => 49, "localized_name" => "Recipe: Phase Boots", "name" => "item_recipe_phase_boots", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    140 => %{"id" => 140, "localized_name" => "Recipe: Daedalus", "name" => "item_recipe_greater_crit", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    152 => %{"id" => 152, "localized_name" => "Shadow Blade", "name" => "item_invis_sword", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    201 => %{"id" => 201, "localized_name" => "Dagon", "name" => "item_dagon_2", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    177 => %{"id" => 177, "localized_name" => "Recipe: Soul Ring", "name" => "item_recipe_soul_ring", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    219 => %{"id" => 219, "localized_name" => "Recipe: Boots of Travel", "name" => "item_recipe_travel_boots_2", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    198 => %{"id" => 198, "localized_name" => "Recipe: Dagon", "name" => "item_recipe_dagon_3", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    1010 => %{"id" => 1010, "localized_name" => "Xmas Stocking", "name" => "item_winter_stocking", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    106 => %{"id" => 106, "localized_name" => "Necronomicon", "name" => "item_necronomicon", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    180 => %{"id" => 180, "localized_name" => "Arcane Boots", "name" => "item_arcane_boots", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    41 => %{"id" => 41, "localized_name" => "Bottle", "name" => "item_bottle", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    211 => %{"id" => 211, "localized_name" => "Recipe: Ring of Aquila", "name" => "item_recipe_ring_of_aquila", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    184 => %{"id" => 184, "localized_name" => "Recipe: Drum of Endurance", "name" => "item_recipe_ancient_janggo", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    118 => %{"id" => 118, "localized_name" => "Recipe: Shiva's Guard", "name" => "item_recipe_shivas_guard", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    229 => %{"id" => 229, "localized_name" => "Solar Crest", "name" => "item_solar_crest", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    91 => %{"id" => 91, "localized_name" => "Recipe: Urn of Shadows", "name" => "item_recipe_urn_of_shadows", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    87 => %{"id" => 87, "localized_name" => "Recipe: Ring of Basilius", "name" => "item_recipe_ring_of_basilius", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    168 => %{"id" => 168, "localized_name" => "Desolator", "name" => "item_desolator", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1006 => %{"id" => 1006, "localized_name" => "DOTA_Tooltip_Ability_item_halloween_rapier", "name" => "item_halloween_rapier", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    33 => %{"id" => 33, "localized_name" => "Cheese", "name" => "item_cheese", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    185 => %{"id" => 185, "localized_name" => "Drum of Endurance", "name" => "item_ancient_janggo", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    166 => %{"id" => 166, "localized_name" => "Maelstrom", "name" => "item_maelstrom", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    209 => %{"id" => 209, "localized_name" => "Recipe: Heaven's Halberd", "name" => "item_recipe_heavens_halberd", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    1014 => %{"id" => 1014, "localized_name" => "Cocoa with Marshmallows", "name" => "item_winter_coco", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    42 => %{"id" => 42, "localized_name" => "Observer Ward", "name" => "item_ward_observer", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    189 => %{"id" => 189, "localized_name" => "Recipe: Veil of Discord", "name" => "item_recipe_veil_of_discord", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    233 => %{"id" => 233, "localized_name" => "Recipe: Aether Lens", "name" => "item_recipe_aether_lens", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    74 => %{"id" => 74, "localized_name" => "Recipe: Wraith Band", "name" => "item_recipe_wraith_band", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    120 => %{"id" => 120, "localized_name" => "Recipe: Bloodstone", "name" => "item_recipe_bloodstone", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    133 => %{"id" => 133, "localized_name" => "Divine Rapier", "name" => "item_rapier", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    264 => %{"id" => 264, "localized_name" => "Banana", "name" => "item_banana", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1000 => %{"id" => 1000, "localized_name" => "Greevil Taffy", "name" => "item_halloween_candy_corn", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    113 => %{"id" => 113, "localized_name" => "Recipe: Heart of Tarrasque", "name" => "item_recipe_heart", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    241 => %{"id" => 241, "localized_name" => "Tango (Shared)", "name" => "item_tango_single", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    204 => %{"id" => 204, "localized_name" => "Dagon", "name" => "item_dagon_5", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    243 => %{"id" => 243, "localized_name" => "Recipe: Crimson Guard", "name" => "item_recipe_crimson_guard", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    60 => %{"id" => 60, "localized_name" => "Point Booster", "name" => "item_point_booster", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    43 => %{"id" => 43, "localized_name" => "Sentry Ward", "name" => "item_ward_sentry", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    10 => %{"id" => 10, "localized_name" => "Quarterstaff", "name" => "item_quarterstaff", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    70 => %{"id" => 70, "localized_name" => "Recipe: Poor Man's Shield", "name" => "item_recipe_poor_mans_shield", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    9 => %{"id" => 9, "localized_name" => "Platemail", "name" => "item_platemail", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    72 => %{"id" => 72, "localized_name" => "Recipe: Bracer", "name" => "item_recipe_bracer", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    132 => %{"id" => 132, "localized_name" => "Recipe: Divine Rapier", "name" => "item_recipe_rapier", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    208 => %{"id" => 208, "localized_name" => "Abyssal Blade", "name" => "item_abyssal_blade", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    123 => %{"id" => 123, "localized_name" => "Linken's Sphere", "name" => "item_sphere", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    121 => %{"id" => 121, "localized_name" => "Bloodstone", "name" => "item_bloodstone", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    86 => %{"id" => 86, "localized_name" => "Buckler", "name" => "item_buckler", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    19 => %{"id" => 19, "localized_name" => "Robe of the Magi", "name" => "item_robe", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    144 => %{"id" => 144, "localized_name" => "Recipe: Battle Fury", "name" => "item_recipe_bfury", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    250 => %{"id" => 250, "localized_name" => "Bloodthorn", "name" => "item_bloodthorn", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    56 => %{"id" => 56, "localized_name" => "Ring of Health", "name" => "item_ring_of_health", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    147 => %{"id" => 147, "localized_name" => "Manta Style", "name" => "item_manta", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    262 => %{"id" => 262, "localized_name" => "Recipe: Hurricane Pike", "name" => "item_recipe_hurricane_pike", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    247 => %{"id" => 247, "localized_name" => "Moon Shard", "name" => "item_moon_shard", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    116 => %{"id" => 116, "localized_name" => "Black King Bar", "name" => "item_black_king_bar", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    252 => %{"id" => 252, "localized_name" => "Echo Sabre", "name" => "item_echo_sabre", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    218 => %{"id" => 218, "localized_name" => "Observer and Sentry Wards", "name" => "item_ward_dispenser", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    95 => %{"id" => 95, "localized_name" => "Recipe: Scythe of Vyse", "name" => "item_recipe_sheepstick", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    115 => %{"id" => 115, "localized_name" => "Recipe: Black King Bar", "name" => "item_recipe_black_king_bar", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    249 => %{"id" => 249, "localized_name" => "Silver Edge", "name" => "item_silver_edge", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    251 => %{"id" => 251, "localized_name" => "Recipe: Echo Sabre", "name" => "item_recipe_echo_sabre", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    128 => %{"id" => 128, "localized_name" => "Recipe: Soul Booster", "name" => "item_recipe_soul_booster", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    57 => %{"id" => 57, "localized_name" => "Void Stone", "name" => "item_void_stone", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    167 => %{"id" => 167, "localized_name" => "Recipe: Desolator", "name" => "item_recipe_desolator", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    51 => %{"id" => 51, "localized_name" => "Demon Edge", "name" => "item_demon_edge", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    179 => %{"id" => 179, "localized_name" => "Recipe: Arcane Boots", "name" => "item_recipe_arcane_boots", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    101 => %{"id" => 101, "localized_name" => "Recipe: Force Staff", "name" => "item_recipe_force_staff", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    200 => %{"id" => 200, "localized_name" => "Recipe: Dagon", "name" => "item_recipe_dagon_5", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    14 => %{"id" => 14, "localized_name" => "Slippers of Agility", "name" => "item_slippers", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    148 => %{"id" => 148, "localized_name" => "Recipe: Crystalys", "name" => "item_recipe_lesser_crit", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    5 => %{"id" => 5, "localized_name" => "Claymore", "name" => "item_claymore", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    54 => %{"id" => 54, "localized_name" => "Sacred Relic", "name" => "item_relic", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    203 => %{"id" => 203, "localized_name" => "Dagon", "name" => "item_dagon_4", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    18 => %{"id" => 18, "localized_name" => "Band of Elvenskin", "name" => "item_boots_of_elves", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    227 => %{"id" => 227, "localized_name" => "Recipe: Solar Crest", "name" => "item_recipe_solar_crest", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    240 => %{"id" => 240, "localized_name" => "Blight Stone", "name" => "item_blight_stone", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    1009 => %{"id" => 1009, "localized_name" => "A Gift!", "name" => "item_present", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    61 => %{"id" => 61, "localized_name" => "Vitality Booster", "name" => "item_vitality_booster", "recipe" => 0, "secret_shop" => 1, "side_shop" => 1},
    103 => %{"id" => 103, "localized_name" => "Recipe: Dagon", "name" => "item_recipe_dagon", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    31 => %{"id" => 31, "localized_name" => "Cloak", "name" => "item_cloak", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    135 => %{"id" => 135, "localized_name" => "Monkey King Bar", "name" => "item_monkey_king_bar", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    146 => %{"id" => 146, "localized_name" => "Recipe: Manta Style", "name" => "item_recipe_manta", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    22 => %{"id" => 22, "localized_name" => "Blade of Alacrity", "name" => "item_blade_of_alacrity", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    29 => %{"id" => 29, "localized_name" => "Boots of Speed", "name" => "item_boots", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    170 => %{"id" => 170, "localized_name" => "Yasha", "name" => "item_yasha", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    114 => %{"id" => 114, "localized_name" => "Heart of Tarrasque", "name" => "item_heart", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    173 => %{"id" => 173, "localized_name" => "Recipe: Diffusal Blade", "name" => "item_recipe_diffusal_blade", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    97 => %{"id" => 97, "localized_name" => "Recipe: Orchid Malevolence", "name" => "item_recipe_orchid", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    21 => %{"id" => 21, "localized_name" => "Ogre Club", "name" => "item_ogre_axe", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    89 => %{"id" => 89, "localized_name" => "Recipe: Pipe of Insight", "name" => "item_recipe_pipe", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    215 => %{"id" => 215, "localized_name" => "Shadow Amulet", "name" => "item_shadow_amulet", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    27 => %{"id" => 27, "localized_name" => "Ring of Regen", "name" => "item_ring_of_regen", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    117 => %{"id" => 117, "localized_name" => "Aegis of the Immortal", "name" => "item_aegis", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    107 => %{"id" => 107, "localized_name" => "Recipe: Aghanim's Scepter", "name" => "item_recipe_ultimate_scepter", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    24 => %{"id" => 24, "localized_name" => "Ultimate Orb", "name" => "item_ultimate_orb", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    47 => %{"id" => 47, "localized_name" => "Recipe: Boots of Travel", "name" => "item_recipe_travel_boots", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    100 => %{"id" => 100, "localized_name" => "Eul's Scepter of Divinity", "name" => "item_cyclone", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    40 => %{"id" => 40, "localized_name" => "Dust of Appearance", "name" => "item_dust", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    206 => %{"id" => 206, "localized_name" => "Rod of Atos", "name" => "item_rod_of_atos", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    96 => %{"id" => 96, "localized_name" => "Scythe of Vyse", "name" => "item_sheepstick", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    131 => %{"id" => 131, "localized_name" => "Hood of Defiance", "name" => "item_hood_of_defiance", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    73 => %{"id" => 73, "localized_name" => "Bracer", "name" => "item_bracer", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    183 => %{"id" => 183, "localized_name" => "Recipe: Shadow Blade", "name" => "item_recipe_invis_sword", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    90 => %{"id" => 90, "localized_name" => "Pipe of Insight", "name" => "item_pipe", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    30 => %{"id" => 30, "localized_name" => "Gem of True Sight", "name" => "item_gem", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    58 => %{"id" => 58, "localized_name" => "Mystic Staff", "name" => "item_mystic_staff", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    80 => %{"id" => 80, "localized_name" => "Recipe: Vladmir's Offering", "name" => "item_recipe_vladmir", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    187 => %{"id" => 187, "localized_name" => "Medallion of Courage", "name" => "item_medallion_of_courage", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    88 => %{"id" => 88, "localized_name" => "Ring of Basilius", "name" => "item_ring_of_basilius", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1020 => %{"id" => 1020, "localized_name" => "Greevil Blink Bone", "name" => "item_winter_greevil_chewy", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    59 => %{"id" => 59, "localized_name" => "Energy Booster", "name" => "item_energy_booster", "recipe" => 0, "secret_shop" => 1, "side_shop" => 1},
    77 => %{"id" => 77, "localized_name" => "Null Talisman", "name" => "item_null_talisman", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    226 => %{"id" => 226, "localized_name" => "Lotus Orb", "name" => "item_lotus_orb", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    23 => %{"id" => 23, "localized_name" => "Staff of Wizardry", "name" => "item_staff_of_wizardry", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    28 => %{"id" => 28, "localized_name" => "Sage's Mask", "name" => "item_sobi_mask", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    46 => %{"id" => 46, "localized_name" => "Town Portal Scroll", "name" => "item_tpscroll", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    171 => %{"id" => 171, "localized_name" => "Recipe: Mask of Madness", "name" => "item_recipe_mask_of_madness", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    210 => %{"id" => 210, "localized_name" => "Heaven's Halberd", "name" => "item_heavens_halberd", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    102 => %{"id" => 102, "localized_name" => "Force Staff", "name" => "item_force_staff", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1015 => %{"id" => 1015, "localized_name" => "Clove Studded Ham", "name" => "item_winter_ham", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    108 => %{"id" => 108, "localized_name" => "Aghanim's Scepter", "name" => "item_ultimate_scepter", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    246 => %{"id" => 246, "localized_name" => "Recipe: Moon Shard", "name" => "item_recipe_moon_shard", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    124 => %{"id" => 124, "localized_name" => "Recipe: Vanguard", "name" => "item_recipe_vanguard", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    153 => %{"id" => 153, "localized_name" => "Recipe: Sange and Yasha", "name" => "item_recipe_sange_and_yasha", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    237 => %{"id" => 237, "localized_name" => "Faerie Fire", "name" => "item_faerie_fire", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    134 => %{"id" => 134, "localized_name" => "Recipe: Monkey King Bar", "name" => "item_recipe_monkey_king_bar", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    213 => %{"id" => 213, "localized_name" => "Recipe: Tranquil Boots", "name" => "item_recipe_tranquil_boots", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    112 => %{"id" => 112, "localized_name" => "Assault Cuirass", "name" => "item_assault", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    92 => %{"id" => 92, "localized_name" => "Urn of Shadows", "name" => "item_urn_of_shadows", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    169 => %{"id" => 169, "localized_name" => "Recipe: Yasha", "name" => "item_recipe_yasha", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    160 => %{"id" => 160, "localized_name" => "Eye of Skadi", "name" => "item_skadi", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1005 => %{"id" => 1005, "localized_name" => "DOTA_Tooltip_Ability_item_mystery_vacuum", "name" => "item_mystery_vacuum", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0}, 
    157 => %{"id" => 157, "localized_name" => "Recipe: Mjollnir", "name" => "item_recipe_mjollnir", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    188 => %{"id" => 188, "localized_name" => "Smoke of Deceit", "name" => "item_smoke_of_deceit", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    53 => %{"id" => 53, "localized_name" => "Reaver", "name" => "item_reaver", "recipe" => 0, "secret_shop" => 1, "side_shop" => 0},
    93 => %{"id" => 93, "localized_name" => "Recipe: Headdress", "name" => "item_recipe_headdress", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    149 => %{"id" => 149, "localized_name" => "Crystalys", "name" => "item_lesser_crit", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    220 => %{"id" => 220, "localized_name" => "Boots of Travel", "name" => "item_travel_boots_2", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    127 => %{"id" => 127, "localized_name" => "Blade Mail", "name" => "item_blade_mail", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1016 => %{"id" => 1016, "localized_name" => "Kringle", "name" => "item_winter_kringle", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    216 => %{"id" => 216, "localized_name" => "Enchanted Mango", "name" => "item_enchanted_mango", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    151 => %{"id" => 151, "localized_name" => "Armlet of Mordiggian", "name" => "item_armlet", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    197 => %{"id" => 197, "localized_name" => "Recipe: Dagon", "name" => "item_recipe_dagon_2", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    1003 => %{"id" => 1003, "localized_name" => "DOTA_Tooltip_Ability_item_mystery_missile", "name" => "item_mystery_missile", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    228 => %{"id" => 228, "localized_name" => "Recipe: Octarine Core", "name" => "item_recipe_octarine_core", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    110 => %{"id" => 110, "localized_name" => "Refresher Orb", "name" => "item_refresher", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    16 => %{"id" => 16, "localized_name" => "Iron Branch", "name" => "item_branches", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    159 => %{"id" => 159, "localized_name" => "Recipe: Eye of Skadi", "name" => "item_recipe_skadi", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    182 => %{"id" => 182, "localized_name" => "Stout Shield", "name" => "item_stout_shield", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    38 => %{"id" => 38, "localized_name" => "Clarity", "name" => "item_clarity", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    142 => %{"id" => 142, "localized_name" => "Recipe: Skull Basher", "name" => "item_recipe_basher", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    257 => %{"id" => 257, "localized_name" => "Tome of Knowledge", "name" => "item_tome_of_knowledge", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    155 => %{"id" => 155, "localized_name" => "Recipe: Satanic", "name" => "item_recipe_satanic", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0},
    174 => %{"id" => 174, "localized_name" => "Diffusal Blade", "name" => "item_diffusal_blade", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    4 => %{"id" => 4, "localized_name" => "Chainmail", "name" => "item_chainmail", "recipe" => 0, "secret_shop" => 0, "side_shop" => 1},
    1004 => %{"id" => 1004, "localized_name" => "DOTA_Tooltip_Ability_item_mystery_toss", "name" => "item_mystery_toss", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    1002 => %{"id" => 1002, "localized_name" => "DOTA_Tooltip_Ability_item_mystery_arrow", "name" => "item_mystery_arrow", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    12 => %{"id" => 12, "localized_name" => "Ring of Protection", "name" => "item_ring_of_protection", "recipe" => 0, "secret_shop" => 0, "side_shop" => 0},
    234 => %{"id" => 234, "localized_name" => "Recipe: Dragon Lance", "name" => "item_recipe_dragon_lance", "recipe" => 1, "secret_shop" => 0, "side_shop" => 0}
  }
  
  def get(id), do: @items[id]

  def localized_name(id), do: @items[id]["localized_name"]

  def name(id), do: @items[id]["name"]

  def recipe?(id), do: @items[id]["recipe"] == 1

  def secret_shop?(id), do: @items[id]["secret_shop"] == 1

  def side_shop?(id), do: @items[id]["side_shop"] == 1

  def all, do: @items

end